#spring:
#  application:
#    name: GATEWAY-SERVICE
#
#
#
#server:
#  port: 9191
#
#  spring:
#    application:
#      name: API-GATEWAY
#
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    instance:
#      hostname: localhost
#
##//routing services
#
#
#  cloud:
#    gateway:
#      routes:
#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#            filters:
#              - name: CircuitBreaker
#                args:
#                  name: USER-SERVICE
#                  fallbackuri: forward:/userServiceFallBack
#
#            - id: DEPARTMENT-SERVICE
#              uri: lb://DEPARTMENT-SERVICE
#              predicates:
#                - Path=/departments/**
#                Setting error or unresponse fallback ruis
#                filters:
#                  - name: CircuitBreaker
#                    args:
#                      name: DEPARTMENT-SERVICE
#                      fallbackuri: forward:/departmentServiceFallBack
#
##                      Hystrix configuration to manage fallback , API max response time is 4000 mils
#      hystrix:
#        command:
#          fallbackcmd:
#            execution:
#              isolation:
#                thread:
#                  timeoutInMilliseconds: 4000
#
#
#
